// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Schema operations need the session pooler (5432), not the transaction
    // pooler (6543) used by runtime queries.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
