<script setup lang="ts">
const sesion=ref<{nombre:string;expiraAt:string}|null>(null), codigo=ref(''), nombre=ref(''), area=ref(''), rollos=ref<number|null>(null), id=ref(''), busy=ref(false), error=ref(''), enviado=ref('')
async function activar(){busy.value=true;error.value='';try{sesion.value=await $fetch<{nombre:string;expiraAt:string}>('/api/stretch-publico/sesion',{method:'POST',body:{codigo:codigo.value.trim()}});codigo.value=''}catch(e:any){error.value=e.data?.statusMessage??'No se pudo activar'}finally{busy.value=false}}
async function enviar(){if(busy.value)return;busy.value=true;error.value='';try{const r=await $fetch<{id:string}>('/api/stretch-publico/pedido',{method:'POST',body:{id:id.value,solicitante:nombre.value,destino:area.value,tipo:'INTERNO',rollos:rollos.value}});enviado.value=`Solicitud ${r.id.slice(0,8)} recibida. Eduardo o Felipe la procesarán.`;nombre.value='';area.value='';rollos.value=null;id.value=crypto.randomUUID()}catch(e:any){error.value=e.data?.statusMessage??'No se pudo enviar. Intenta nuevamente.';if(e.status===401||e.status===403)sesion.value=null}finally{busy.value=false}}
onMounted(async()=>{id.value=crypto.randomUUID();try{sesion.value=await $fetch<{nombre:string;expiraAt:string}>('/api/stretch-publico/sesion')}catch{}})
</script>
<template><main class="solicitud"><div class="card"><strong>Grupo Ambiente · CEDI</strong><h1>Solicitar Stretch film</h1><p>Uso interno · cantidades en rollos</p><p v-if="error" role="alert">{{error}}</p><p v-if="enviado" role="status">{{enviado}}</p><form v-if="!sesion" @submit.prevent="activar"><label>Código de activación del equipo<input v-model="codigo" required autocomplete="off" /></label><button :disabled="busy">Activar pantalla</button></form><form v-else @submit.prevent="enviar"><p>{{sesion.nombre}}</p><fieldset :disabled="busy"><label>Tu nombre<input v-model="nombre" required minlength="3" maxlength="120" autocomplete="off" /></label><label>Área solicitante<input v-model="area" required minlength="2" maxlength="160" autocomplete="off" /></label><label>Cantidad de rollos<input v-model.number="rollos" type="number" min="1" max="1000000" step="1" required /></label><button>{{busy?'Enviando…':'Enviar solicitud'}}</button></fieldset></form></div></main></template>
<style scoped>
.solicitud{min-height:100dvh;background:#0e1725;color:#edf5f3;display:grid;place-items:center;padding:24px;box-sizing:border-box;font-family:system-ui}.card{width:100%;max-width:480px;padding:28px;background:#172334;border:1px solid #344357;border-radius:18px;box-sizing:border-box}strong{color:#14dba0}h1{font-size:26px}p{line-height:1.5;overflow-wrap:anywhere}label{display:grid;gap:8px;margin:20px 0}input,button{font:inherit;padding:14px;border-radius:9px;border:1px solid #536275;box-sizing:border-box;min-width:0;width:100%}button{background:#14dba0;color:#07261c;font-weight:700;cursor:pointer}button:disabled{opacity:.6}fieldset{border:0;padding:0;min-width:0}:focus-visible{outline:3px solid #14dba0;outline-offset:3px}
</style>
