-- Migration disabled.
-- This old tienda status migration is obsolete and conflicts with the simplified Sprint 8 flow.
-- Use prisma/migrate-sprint8-simplified.sql and prisma/migrate-sprint8-guardado-pendiente.sql instead.
