import { beforeEach, describe, expect, it, vi } from 'vitest'
const m=vi.hoisted(()=>({auth:vi.fn(),body:vi.fn(),cookie:vi.fn(),tx:vi.fn(),user:{findUnique:vi.fn(),findMany:vi.fn()},acceso:{findUnique:vi.fn(),findMany:vi.fn()},stock:{upsert:vi.fn(),update:vi.fn()},pedido:{findUnique:vi.fn(),create:vi.fn(),update:vi.fn(),count:vi.fn()},mov:{findUnique:vi.fn(),create:vi.fn()},sesion:{findUnique:vi.fn(),create:vi.fn(),update:vi.fn()},log:{create:vi.fn()},noti:{create:vi.fn(),createMany:vi.fn()},lock:vi.fn()}))
vi.mock('../../nuxt-app/node_modules/h3/dist/index.mjs',()=>({defineEventHandler:(f:unknown)=>f,readBody:m.body,getCookie:m.cookie,createError:(o:object)=>Object.assign(new Error(),o)}))
vi.mock('../../nuxt-app/server/utils/auth',()=>({requireAuth:m.auth}))
vi.mock('../../nuxt-app/server/utils/prisma',()=>({prisma:{$transaction:m.tx,user:m.user,stretchAcceso:m.acceso}}))
import accion from '../../nuxt-app/server/api/stretch-film/accion.post'
import publico from '../../nuxt-app/server/api/stretch-publico/pedido.post'
const event={} as Parameters<typeof accion>[0], id='11111111-1111-4111-8111-111111111111'
const pedido=()=>({id,usuarioId:'viviana',solicitante:'Viviana',destino:'Tienda 1',tipo:'TIENDA',rollos:8,estado:'PENDIENTE'})
beforeEach(()=>{
  vi.resetAllMocks();m.auth.mockResolvedValue({id:'felipe',name:'Felipe'});m.user.findUnique.mockResolvedValue({active:true});m.user.findMany.mockResolvedValue([{id:'felipe'}]);m.acceso.findUnique.mockResolvedValue({gestionar:true,solicitar:true});m.acceso.findMany.mockResolvedValue([{userId:'felipe'}]);m.stock.upsert.mockResolvedValue({rollos:10});m.pedido.findUnique.mockResolvedValue(pedido())
  m.tx.mockImplementation(cb=>cb({$executeRaw:m.lock,user:m.user,stretchAcceso:m.acceso,stretchStock:m.stock,stretchPedido:m.pedido,stretchMovimiento:m.mov,stretchSesion:m.sesion,activityLog:m.log,notificacion:m.noti}))
})
describe('Stretch: inventario, permisos y sesión compartida',()=>{
  it('entrega y descuenta dentro de la transacción, dejando saldo y responsable',async()=>{m.body.mockResolvedValue({accion:'procesar',pedidoId:id});await accion(event);expect(m.lock).toHaveBeenCalledOnce();expect(m.stock.update).toHaveBeenCalledWith({where:{id:'principal'},data:{rollos:2}});expect(m.mov.create).toHaveBeenCalledWith({data:expect.objectContaining({cantidad:-8,saldo:2,pedidoId:id,usuarioId:'felipe'})})})
  it('no descuenta un pedido ya procesado',async()=>{m.pedido.findUnique.mockResolvedValue({...pedido(),estado:'ENTREGADO'});m.body.mockResolvedValue({accion:'procesar',pedidoId:id});await expect(accion(event)).rejects.toMatchObject({statusCode:409});expect(m.stock.update).not.toHaveBeenCalled()})
  it('no permite saldos negativos',async()=>{m.stock.upsert.mockResolvedValue({rollos:2});m.body.mockResolvedValue({accion:'procesar',pedidoId:id});await expect(accion(event)).rejects.toMatchObject({statusCode:409});expect(m.mov.create).not.toHaveBeenCalled()})
  it('Viviana solicita pero no puede administrar stock',async()=>{m.acceso.findUnique.mockResolvedValue({solicitar:true,gestionar:false});m.body.mockResolvedValue({accion:'entrada',id,rollos:20,motivo:'Ingreso'});await expect(accion(event)).rejects.toMatchObject({statusCode:403});expect(m.tx).not.toHaveBeenCalled()})
  it('una cuenta desactivada pierde acceso aunque conserve permiso',async()=>{m.user.findUnique.mockResolvedValue({active:false});await expect(accion(event)).rejects.toMatchObject({statusCode:403})})
  it('rechaza fracciones de rollo',async()=>{m.body.mockResolvedValue({accion:'entrada',id,rollos:1.5,motivo:'Ingreso'});await expect(accion(event)).rejects.toMatchObject({statusCode:400})})
  it('el ajuste guarda diferencia frente a existencia anterior',async()=>{m.mov.findUnique.mockResolvedValue(null);m.body.mockResolvedValue({accion:'ajuste',id,rollos:7,motivo:'Conteo físico'});await accion(event);expect(m.mov.create).toHaveBeenCalledWith({data:expect.objectContaining({cantidad:-3,saldo:7,tipo:'AJUSTE'})})})
  it('un reintento de entrada no suma por segunda vez',async()=>{m.mov.findUnique.mockResolvedValue({usuarioId:'felipe',tipo:'ENTRADA',cantidad:20});m.body.mockResolvedValue({accion:'entrada',id,rollos:20,motivo:'Ingreso'});await accion(event);expect(m.stock.update).not.toHaveBeenCalled()})
  it('la pantalla compartida exige sesión válida',async()=>{m.body.mockResolvedValue({id,solicitante:'Persona CEDI',destino:'Área A',tipo:'INTERNO',rollos:2});m.cookie.mockReturnValue(undefined);await expect(publico(event)).rejects.toMatchObject({statusCode:401});expect(m.pedido.create).not.toHaveBeenCalled()})
  it('una sesión vencida no crea pedidos',async()=>{m.body.mockResolvedValue({id,solicitante:'Persona CEDI',destino:'Área A',tipo:'INTERNO',rollos:2});m.cookie.mockReturnValue('a'.repeat(64));m.sesion.findUnique.mockResolvedValue({id:'s',activada:true,expiraAt:new Date(0)});await expect(publico(event)).rejects.toMatchObject({statusCode:401})})
  it('la sesión compartida solo crea pedidos internos sin tocar existencias',async()=>{m.body.mockResolvedValue({id,solicitante:'Persona CEDI',destino:'Área A',tipo:'INTERNO',rollos:2});m.cookie.mockReturnValue('a'.repeat(64));m.sesion.findUnique.mockResolvedValue({id:'s',creadaPorId:'felipe',activada:true,expiraAt:new Date(Date.now()+3600000)});m.pedido.findUnique.mockResolvedValue(null);m.pedido.count.mockResolvedValue(0);await publico(event);expect(m.pedido.create).toHaveBeenCalledWith({data:expect.objectContaining({sesionId:'s',tipo:'INTERNO',rollos:2})});expect(m.stock.update).not.toHaveBeenCalled()})
})
